# Site settings
title: code for coffee
email: james@codeforcoffee.org
description: > # this means to ignore newlines until "baseurl:"
  The professional website of James Traver
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://code-for-coffee.github.io" # the base hostname & protocol for your site
twitter_username: code4coffee
github_username:  code-for-coffee
# Build settings
markdown: kramdown
permalink: /:title
disqus_shortname: codeforcoffee
exclude: [structz/]
